[package]
name = "octocrab"
version = "0.1.0"
authors = ["XAMPPRocky <xampprocky@gmail.com>"]
edition = "2018"
description = "WIP"
license = "Apache-2.0/MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10.4", features = ["json"] }
tokio = { version = "0.2.17", features = ["full"] }
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.51"
async-trait = "0.1.30"
chrono = { version = "0.4.11", features = ["serde"] }
url = "2.1.1"
hyperx = "1.0.0"
