[package]
name = "octocrab"
version = "0.1.0"
authors = ["XAMPPRocky <xampprocky@gmail.com>"]
edition = "2018"
description = "WIP"
license = "Apache-2.0/MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
